#ifndef DEFINES_H_
#define DEFINES_H_

enum BATTERY_STATES
{
    BATTERY_NONE,
    BATTERY_CHARGING_10,
    BATTERY_CHARGING_20,
    BATTERY_CHARGING_30,
    BATTERY_CHARGING_40,
    BATTERY_CHARGING_50,
    BATTERY_CHARGING_60,
    BATTERY_CHARGING_70,
    BATTERY_CHARGING_80,
    BATTERY_CHARGING_90,
    BATTERY_CHARGING_100,
    BATTERY_DISCHARGING_10,
    BATTERY_DISCHARGING_20,
    BATTERY_DISCHARGING_30,
    BATTERY_DISCHARGING_40,
    BATTERY_DISCHARGING_50,
    BATTERY_DISCHARGING_60,
    BATTERY_DISCHARGING_70,
    BATTERY_DISCHARGING_80,
    BATTERY_DISCHARGING_90,
    BATTERY_DISCHARGING_100
};

enum BLUETOOTH_STATES
{
    BLUETOOTH_NONE,
    BLUETOOTH_DISABLED,
    BLUETOOTH_ACTIVE,
    BLUETOOTH_CONNECTED
};

enum SIM_STATES
{
    SIM_NONE,
    SIM_ACTIVE,
    SIM_MISSING
};

#endif /* DEFINES_H_ */
